# Generated by Django 5.2.4 on 2025-08-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoredArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wp_post_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("wp_permalink", models.URLField(blank=True, null=True)),
                ("subject", models.CharField(max_length=255)),
                ("genre", models.CharField(blank=True, max_length=120)),
                ("tone", models.CharField(blank=True, max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("html", models.TextField()),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("stored_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(default="wordpress", max_length=64)),
                ("billing_plan", models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
