# Generated by Django 5.2.7 on 2025-12-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postpress_ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=128, unique=True)),
                (
                    "plan_slug",
                    models.CharField(
                        choices=[
                            ("solo", "Solo"),
                            ("creator", "Creator"),
                            ("studio", "Studio"),
                            ("agency", "Agency (AI Included)"),
                            ("agency_byo", "Agency Unlimited (BYO Key)"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("canceled", "Canceled"),
                            ("expired", "Expired"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("max_sites", models.PositiveIntegerField(blank=True, null=True)),
                ("unlimited_sites", models.BooleanField(default=False)),
                ("byo_key_required", models.BooleanField(default=False)),
                ("ai_included", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["key"], name="postpress_a_key_314f4d_idx"),
                    models.Index(
                        fields=["status", "plan_slug"],
                        name="postpress_a_status_6c979b_idx",
                    ),
                ],
            },
        ),
    ]
