# Generated by Django 5.2.7 on 2025-12-24 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postpress_ai", "0002_license"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_url", models.URLField(max_length=255)),
                (
                    "site_fingerprint",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activations",
                        to="postpress_ai.license",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["site_url"], name="postpress_a_site_ur_4e5df1_idx"
                    ),
                    models.Index(
                        fields=["last_verified_at"],
                        name="postpress_a_last_ve_ea9268_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("license", "site_url"),
                        name="unique_activation_per_license_site",
                    )
                ],
            },
        ),
    ]
