# Generated by Django 5.2.7 on 2025-12-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postpress_ai", "0003_activation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_event_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stripe webhook event id that created/updated this order (if applicable).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "stripe_session_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stripe Checkout Session id (cs_...).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stripe Customer id (cus_...) if present.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stripe PaymentIntent id (pi_...) if present.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "purchaser_name",
                    models.CharField(
                        blank=True,
                        help_text="Name captured by Stripe Checkout (if provided).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "purchaser_email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        help_text="Email captured by Stripe Checkout (if provided).",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "amount_total",
                    models.IntegerField(
                        blank=True,
                        help_text="Total amount in the smallest currency unit (e.g., cents).",
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        help_text="Currency (e.g., 'usd').",
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_index=True,
                        default="created",
                        help_text="Order lifecycle status (e.g., created, paid, fulfilled, failed).",
                        max_length=64,
                    ),
                ),
                (
                    "raw_session",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of the Stripe Checkout Session payload at time of processing.",
                        null=True,
                    ),
                ),
                (
                    "raw_event",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of the Stripe webhook event payload at time of processing.",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for debugging/audit (never shown to users).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["stripe_session_id"],
                        name="postpress_a_stripe__2e8a53_idx",
                    ),
                    models.Index(
                        fields=["stripe_customer_id"],
                        name="postpress_a_stripe__1d8088_idx",
                    ),
                    models.Index(
                        fields=["stripe_payment_intent_id"],
                        name="postpress_a_stripe__4b6618_idx",
                    ),
                    models.Index(
                        fields=["purchaser_email"],
                        name="postpress_a_purchas_6dfd70_idx",
                    ),
                    models.Index(
                        fields=["status"], name="postpress_a_status_9e2783_idx"
                    ),
                ],
            },
        ),
    ]
