# Generated by Django 5.2.7 on 2026-01-10 19:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postpress_ai", "0008_entitlement"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditPackPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pack_type",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        max_length=20,
                    ),
                ),
                ("credits_granted", models.PositiveIntegerField(default=0)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "currency",
                    models.CharField(blank=True, default="usd", max_length=10),
                ),
                ("amount_cents", models.PositiveIntegerField(default=0)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_packs",
                        to="postpress_ai.customer",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_packs",
                        to="postpress_ai.license",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_packs",
                        to="postpress_ai.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("monthly_grant", "Monthly Grant"),
                            ("pack_grant", "Pack Grant"),
                            ("spend", "Spend"),
                            ("manual_adjust", "Manual Adjust"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "period_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_ledger",
                        to="postpress_ai.customer",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_ledger",
                        to="postpress_ai.license",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_ledger",
                        to="postpress_ai.subscription",
                    ),
                ),
                (
                    "credit_pack",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="postpress_ai.creditpackpurchase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="creditpackpurchase",
            index=models.Index(
                fields=["pack_type", "created_at"],
                name="postpress_a_pack_ty_b157b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="creditpackpurchase",
            index=models.Index(
                fields=["stripe_payment_intent_id"],
                name="postpress_a_stripe__fce6e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="creditledger",
            index=models.Index(
                fields=["entry_type", "created_at"],
                name="postpress_a_entry_t_53be2e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="creditledger",
            index=models.Index(
                fields=["period_key"], name="postpress_a_period__bf944d_idx"
            ),
        ),
    ]
