# Generated by Django 5.2.7 on 2026-01-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postpress_ai", "0009_creditpackpurchase_creditledger_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="stripe_event_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stripe event id (evt_...) used to prevent duplicate email sends on webhook retries.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="emaillog",
            constraint=models.UniqueConstraint(
                fields=("stripe_event_id", "to_email"),
                name="uniq_email_event_per_recipient",
            ),
        ),
    ]
