# Generated by Django 5.2.7 on 2026-01-26 13:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postpress_ai", "0010_emaillog_stripe_event_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_url",
                    models.CharField(
                        db_index=True,
                        help_text="Normalized scheme://host[:port] (path/query stripped).",
                        max_length=255,
                    ),
                ),
                (
                    "view",
                    models.CharField(
                        db_index=True,
                        help_text="Which endpoint/view produced this usage event (generate/preview/translate).",
                        max_length=64,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True,
                        default="openai",
                        help_text="AI provider identifier (e.g., openai).",
                        max_length=64,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Model name as reported by the provider (optional).",
                        max_length=128,
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Provider request id (if available).",
                        max_length=128,
                    ),
                ),
                (
                    "run_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Provider run id (if available).",
                        max_length=128,
                    ),
                ),
                (
                    "prompt_tokens",
                    models.IntegerField(
                        default=0,
                        help_text="Prompt/input tokens used.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "completion_tokens",
                    models.IntegerField(
                        default=0,
                        help_text="Completion/output tokens used.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_tokens",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Total tokens used (prompt + completion when available).",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "units",
                    models.CharField(
                        default="tokens",
                        help_text="Accounting unit (default: tokens).",
                        max_length=32,
                    ),
                ),
                (
                    "ok",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the AI call completed successfully.",
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short error code for failures (optional).",
                        max_length=64,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific safe metadata (no secrets).",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Event timestamp.",
                    ),
                ),
                (
                    "activation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_events",
                        to="postpress_ai.activation",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_events",
                        to="postpress_ai.license",
                    ),
                ),
            ],
            options={
                "db_table": "ppa_usage_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["license", "created_at"], name="ppa_use_lic_dt"
                    ),
                    models.Index(
                        fields=["site_url", "created_at"], name="ppa_use_site_dt"
                    ),
                    models.Index(fields=["view", "created_at"], name="ppa_use_view_dt"),
                ],
            },
        ),
    ]
