# Generated by Django 5.2.7 on 2026-03-08 22:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postpress_ai", "0011_usageevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("site_url", models.URLField()),
                ("site_token", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connected_sites",
                        to="postpress_ai.license",
                    ),
                ),
            ],
            options={
                "ordering": ["site_url"],
            },
        ),
        migrations.CreateModel(
            name="RemoteDraftLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_site_id_raw", models.CharField(blank=True, max_length=64)),
                ("target_site_id_raw", models.CharField(blank=True, max_length=64)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("remote_post_id", models.CharField(blank=True, max_length=64)),
                ("remote_edit_link", models.TextField(blank=True)),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_draft_logs",
                        to="postpress_ai.license",
                    ),
                ),
                (
                    "source_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remote_drafts_sent",
                        to="postpress_ai.licensesite",
                    ),
                ),
                (
                    "target_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remote_drafts_received",
                        to="postpress_ai.licensesite",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="licensesite",
            index=models.Index(
                fields=["license", "status"], name="postpress_a_license_94b0ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="licensesite",
            index=models.Index(
                fields=["site_url"], name="postpress_a_site_ur_1e2183_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="licensesite",
            constraint=models.UniqueConstraint(
                fields=("license", "site_url"), name="unique_license_site_url"
            ),
        ),
        migrations.AddIndex(
            model_name="remotedraftlog",
            index=models.Index(
                fields=["license", "created_at"], name="postpress_a_license_f86c2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="remotedraftlog",
            index=models.Index(
                fields=["success"], name="postpress_a_success_8628dc_idx"
            ),
        ),
    ]
