# Generated by Django 5.2.7 on 2026-03-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpress_ai', '0012_licensesite_remotedraftlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_slug', models.CharField(db_index=True, default='postpress-ai', max_length=100)),
                ('version', models.CharField(db_index=True, max_length=50)),
                ('zip_file', models.FileField(upload_to='postpress_ai/releases/')),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('changelog', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-released_at', '-id'],
                'indexes': [models.Index(fields=['product_slug', 'is_active'], name='postpress_a_product_63555f_idx')],
                'constraints': [models.UniqueConstraint(fields=('product_slug', 'version'), name='uniq_plugin_release_slug_version')],
            },
        ),
    ]
