# Generated by Django 5.2.4 on 2025-08-05 18:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("response_text", models.TextField(max_length=5000)),
                (
                    "response_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "webdoctor_responses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "session_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        max_length=254,
                        null=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "webdoctor_conversations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "created_at"],
                        name="webdoctor_c_email_659701_idx",
                    ),
                    models.Index(
                        fields=["session_id", "created_at"],
                        name="webdoctor_c_session_81ab60_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("issue_description", models.TextField(max_length=1000)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "webdoctor_interactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "created_at"],
                        name="webdoctor_i_email_1494cb_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="webdoctor_i_created_b00682_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "sender",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("agent", "Agent"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="webdoctor.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "webdoctor_messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "created_at"],
                        name="webdoctor_m_convers_386a86_idx",
                    ),
                    models.Index(
                        fields=["sender", "created_at"],
                        name="webdoctor_m_sender_0cabde_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DiagnosticReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "user_email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("issue_details", models.TextField(max_length=1000)),
                ("report_content", models.TextField(max_length=5000)),
                ("email_sent", models.BooleanField(db_index=True, default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user_interaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="webdoctor.userinteraction",
                    ),
                ),
            ],
            options={
                "db_table": "webdoctor_reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_email", "created_at"],
                        name="webdoctor_r_user_em_c54175_idx",
                    ),
                    models.Index(
                        fields=["email_sent", "created_at"],
                        name="webdoctor_r_email_s_07ed8e_idx",
                    ),
                ],
            },
        ),
    ]
