# Generated by Django 5.2.4 on 2025-08-28 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("humancapital", "0003_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="CognitiveAbility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reasoning",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Logical reasoning score"
                    ),
                ),
                (
                    "memory",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Memory retention score"
                    ),
                ),
                (
                    "problem_solving",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Problem solving ability"
                    ),
                ),
                (
                    "attention",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Attention and focus score"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cognitive_scores",
                        to="humancapital.assessmentsession",
                    ),
                ),
            ],
        ),
    ]
