# Generated by Django 5.2.4 on 2025-08-28 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("humancapital", "0004_cognitiveability"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openness",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Openness to new experiences"
                    ),
                ),
                (
                    "conscientiousness",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Level of organization and dependability"
                    ),
                ),
                (
                    "extraversion",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Sociability and energy orientation"
                    ),
                ),
                (
                    "agreeableness",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Compassion and cooperativeness"
                    ),
                ),
                (
                    "neuroticism",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Tendency toward emotional instability"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personality_profiles",
                        to="humancapital.assessmentsession",
                    ),
                ),
            ],
        ),
    ]
