# Generated by Django 5.2.4 on 2025-08-28 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("humancapital", "0005_personality"),
    ]

    operations = [
        migrations.CreateModel(
            name="Behavior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "communication",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Clarity and style of communication"
                    ),
                ),
                (
                    "decision_making",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Speed and confidence in decisions"
                    ),
                ),
                (
                    "leadership",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Leadership vs. support orientation"
                    ),
                ),
                (
                    "collaboration",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Ability to collaborate effectively"
                    ),
                ),
                (
                    "conflict_handling",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="How the person manages conflict"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_profiles",
                        to="humancapital.assessmentsession",
                    ),
                ),
            ],
        ),
    ]
