# Generated by Django 5.2.4 on 2025-08-28 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("humancapital", "0006_behavior"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achievement",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Drive for success and results"
                    ),
                ),
                (
                    "stability",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Need for security and consistency"
                    ),
                ),
                (
                    "autonomy",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Desire for independence"
                    ),
                ),
                (
                    "recognition",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Need for praise and visibility"
                    ),
                ),
                (
                    "learning",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Motivation to learn and grow"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motivations",
                        to="humancapital.assessmentsession",
                    ),
                ),
            ],
        ),
    ]
