# Generated by Django 5.2.4 on 2025-08-28 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("humancapital", "0007_motivation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        help_text="Which section this question belongs to (e.g., skill, personality, etc.)",
                        max_length=50,
                    ),
                ),
                ("question_text", models.TextField()),
                ("answer_text", models.TextField()),
                ("answer_value", models.FloatField(blank=True, null=True)),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="humancapital.assessmentsession",
                    ),
                ),
            ],
        ),
    ]
