# Generated by Django 5.2.4 on 2025-08-28 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("humancapital", "0008_response"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scorecard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill_index",
                    models.FloatField(
                        default=0,
                        help_text="Overall technical/professional skill score",
                    ),
                ),
                (
                    "cognitive_index",
                    models.FloatField(default=0, help_text="Cognitive ability score"),
                ),
                (
                    "personality_index",
                    models.FloatField(default=0, help_text="Personality balance score"),
                ),
                (
                    "behavior_index",
                    models.FloatField(default=0, help_text="Behavioral style score"),
                ),
                (
                    "motivation_index",
                    models.FloatField(default=0, help_text="Motivation/drive score"),
                ),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorecard",
                        to="humancapital.assessmentsession",
                    ),
                ),
            ],
        ),
    ]
