# Generated by Django 5.2.4 on 2025-08-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("humancapital", "0009_scorecard"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentsession",
            name="ai_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
