# Generated by Django 5.2.4 on 2025-08-28 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("humancapital", "0010_assessmentsession_ai_summary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessmentsession",
            options={"ordering": ["-started_at"]},
        ),
        migrations.RemoveField(
            model_name="assessmentsession",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="assessmentsession",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="assessmentsession",
            name="user",
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="user_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="humancapital.userprofile",
            ),
        ),
    ]
