# Generated by Django 5.2.4 on 2025-08-25 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EvidenceTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Higher = stronger evidence"
                    ),
                ),
            ],
            options={
                "ordering": ("-weight", "name"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PreparationForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("aliases", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
                "indexes": [
                    models.Index(fields=["slug"], name="therapylib__slug_c68889_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("title", models.CharField(max_length=500)),
                ("authors", models.CharField(blank=True, default="", max_length=500)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("journal", models.CharField(blank=True, default="", max_length=255)),
                ("doi", models.CharField(blank=True, default="", max_length=128)),
                ("url", models.URLField(blank=True, default="")),
                ("pmid", models.CharField(blank=True, default="", max_length=32)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["pmid"], name="therapylib__pmid_048729_idx"),
                    models.Index(fields=["doi"], name="therapylib__doi_47c321_idx"),
                    models.Index(fields=["year"], name="therapylib__year_397c1f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("version", models.PositiveIntegerField(db_index=True, default=1)),
                ("summary", models.TextField(blank=True, default="")),
                ("published", models.BooleanField(db_index=True, default=False)),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocols",
                        to="therapylib.condition",
                    ),
                ),
                (
                    "references",
                    models.ManyToManyField(
                        blank=True, related_name="protocols", to="therapylib.reference"
                    ),
                ),
            ],
            options={
                "ordering": ("condition__name", "-version"),
                "unique_together": {("condition", "version")},
            },
        ),
        migrations.CreateModel(
            name="Substance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "synonyms",
                    models.JSONField(
                        blank=True, default=list, help_text="List of alternative names"
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="substances",
                        to="therapylib.category",
                    ),
                ),
                (
                    "forms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="substances",
                        to="therapylib.preparationform",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProtocolItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("first_line", "First-line"),
                            ("adjunct", "Adjunct"),
                            ("experimental", "Experimental"),
                        ],
                        db_index=True,
                        default="first_line",
                        max_length=20,
                    ),
                ),
                (
                    "dose_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable dose",
                        max_length=128,
                    ),
                ),
                ("duration", models.CharField(blank=True, default="", max_length=64)),
                ("rationale", models.TextField(blank=True, default="")),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="therapylib.evidencetag",
                    ),
                ),
                (
                    "preparation_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="therapylib.preparationform",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="therapylib.protocol",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="protocol_items",
                        to="therapylib.substance",
                    ),
                ),
            ],
            options={
                "ordering": ("tier", "sort_order", "substance__name"),
            },
        ),
        migrations.CreateModel(
            name="MonographVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("version", models.PositiveIntegerField(db_index=True, default=1)),
                ("indications", models.TextField(blank=True, default="")),
                ("mechanism", models.TextField(blank=True, default="")),
                ("dosing_overview", models.TextField(blank=True, default="")),
                ("contraindications", models.TextField(blank=True, default="")),
                ("interactions", models.TextField(blank=True, default="")),
                ("adverse_effects", models.TextField(blank=True, default="")),
                ("pregnancy_lactation", models.TextField(blank=True, default="")),
                ("pediatrics", models.TextField(blank=True, default="")),
                ("geriatrics", models.TextField(blank=True, default="")),
                ("lab_markers", models.TextField(blank=True, default="")),
                ("evidence_summary", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "references",
                    models.ManyToManyField(
                        blank=True,
                        related_name="monograph_versions",
                        to="therapylib.reference",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="therapylib.substance",
                    ),
                ),
            ],
            options={
                "ordering": ("substance__name", "-version"),
            },
        ),
        migrations.CreateModel(
            name="Monograph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set after publishing a version.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="as_current_for",
                        to="therapylib.monographversion",
                    ),
                ),
                (
                    "substance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monograph",
                        to="therapylib.substance",
                    ),
                ),
            ],
            options={
                "ordering": ("substance__name",),
            },
        ),
        migrations.CreateModel(
            name="DoseRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "amount_min",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "amount_max",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("unit", models.CharField(help_text="e.g., mg, g, mL", max_length=32)),
                (
                    "frequency",
                    models.CharField(
                        blank=True, default="", help_text="e.g., 2x/day", max_length=64
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, default="", help_text="e.g., 8 weeks", max_length=64
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "monograph_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doses",
                        to="therapylib.monographversion",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doses",
                        to="therapylib.preparationform",
                    ),
                ),
            ],
            options={
                "ordering": ("form__name", "unit"),
                "indexes": [
                    models.Index(fields=["unit"], name="therapylib__unit_bbb0c6_idx")
                ],
                "unique_together": {("monograph_version", "form", "unit")},
            },
        ),
        migrations.AddIndex(
            model_name="substance",
            index=models.Index(fields=["slug"], name="therapylib__slug_5ac085_idx"),
        ),
        migrations.AddIndex(
            model_name="protocolitem",
            index=models.Index(fields=["tier"], name="therapylib__tier_db7fa3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="monographversion",
            unique_together={("substance", "version")},
        ),
    ]
