# Generated by Django 5.2.4 on 2025-07-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = []
