# Generated by Django 5.2.4 on 2025-07-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_first_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "customer_last_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("customer_email", models.EmailField(max_length=254)),
                ("pickup_time", models.DateTimeField()),
                (
                    "order_items",
                    models.JSONField(help_text="Stores items, quantities, options."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Paid", "Paid"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_session_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
