# Generated by Django 5.2.4 on 2025-08-05 18:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tool",
                    models.CharField(
                        choices=[("ad_builder", "Ad Builder")],
                        db_index=True,
                        default="ad_builder",
                        max_length=50,
                    ),
                ),
                (
                    "prompt_text",
                    models.TextField(
                        help_text="The prompt submitted to the AI.",
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "output_text",
                    models.TextField(help_text="The AI-generated content."),
                ),
                (
                    "model_used",
                    models.CharField(db_index=True, default="gpt-4o", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prompt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="promptopilot.adprompt",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                ("product_name", models.CharField(db_index=True, max_length=255)),
                ("audience", models.TextField()),
                ("tone", models.CharField(max_length=100)),
                ("model_used", models.CharField(db_index=True, max_length=50)),
                ("result", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="promptopilo_created_fcbd26_idx"
                    ),
                    models.Index(
                        fields=["product_name"], name="promptopilo_product_49600f_idx"
                    ),
                    models.Index(fields=["tone"], name="promptopilo_tone_68dde7_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="adprompt",
            index=models.Index(
                fields=["created_at"], name="promptopilo_created_6fab01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adprompt",
            index=models.Index(fields=["tool"], name="promptopilo_tool_4214ec_idx"),
        ),
        migrations.AddIndex(
            model_name="adresult",
            index=models.Index(
                fields=["created_at"], name="promptopilo_created_c63816_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adresult",
            index=models.Index(
                fields=["model_used"], name="promptopilo_model_u_50d444_idx"
            ),
        ),
    ]
