# Generated by Django 5.2.4 on 2025-07-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebsiteScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                ("issues_found", models.TextField()),
                ("recommendations", models.TextField()),
            ],
        ),
    ]
